import type { AbilityDef, PlayerClass, Stats, WeaponInfo } from '../types';

// ---------------------------------------------------------------------------
// Player classes — per-level base stats follow vanilla growth curves.
// HP/mana rules are the real ones: first 20 stamina gives 1 hp each, the rest
// 10 hp each; first 20 intellect gives 1 mana each, the rest 15 mana each.
// ---------------------------------------------------------------------------

export interface ClassDef {
  id: PlayerClass;
  name: string;
  baseStats: Stats;
  statsPerLevel: Stats;
  baseHp: number; // class hp before stamina at level 1
  hpPerLevel: number;
  baseMana: number;
  manaPerLevel: number;
  resourceType: 'rage' | 'mana' | 'energy';
  startWeapon: string;
  startChest: string;
  ranged?: WeaponInfo & { maxRange: number; minRange: number }; // hunters: auto shot
  abilities: string[]; // full kit, in learn order
  color: number;
  crest: string; // portrait glyph
}

export const CLASSES: Record<PlayerClass, ClassDef> = {
  warrior: {
    id: 'warrior',
    name: 'Savaşçı',
    baseStats: { str: 23, agi: 20, sta: 22, int: 10, spi: 11, armor: 50 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 0, spi: 0, armor: 12 },
    baseHp: 50,
    hpPerLevel: 18,
    baseMana: 100, // rage cap
    manaPerLevel: 0,
    resourceType: 'rage',
    startWeapon: 'worn_sword',
    startChest: 'recruit_tunic',
    abilities: ['heroic_strike', 'battle_shout', 'charge', 'rend', 'thunder_clap', 'hamstring', 'bloodrage', 'overpower', 'execute', 'slam', 'cleave'],
    color: 0xc79c6e,
    crest: '⚔',
  },
  mage: {
    id: 'mage',
    name: 'Büyücü',
    baseStats: { str: 10, agi: 12, sta: 14, int: 24, spi: 22, armor: 25 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    baseHp: 40,
    hpPerLevel: 12,
    baseMana: 100,
    manaPerLevel: 24,
    resourceType: 'mana',
    startWeapon: 'gnarled_staff',
    startChest: 'apprentice_robe',
    abilities: ['fireball', 'frost_armor', 'arcane_intellect', 'frostbolt', 'conjure_water', 'fire_blast', 'arcane_missiles', 'polymorph', 'frost_nova', 'arcane_explosion', 'scorch', 'ice_barrier'],
    color: 0x69ccf0,
    crest: '✦',
  },
  rogue: {
    id: 'rogue',
    name: 'Haydut',
    baseStats: { str: 17, agi: 25, sta: 17, int: 11, spi: 12, armor: 40 },
    statsPerLevel: { str: 1, agi: 3, sta: 1, int: 0, spi: 0, armor: 8 },
    baseHp: 45,
    hpPerLevel: 15,
    baseMana: 100, // energy cap
    manaPerLevel: 0,
    resourceType: 'energy',
    startWeapon: 'rusty_dagger',
    startChest: 'footpad_jerkin',
    abilities: ['sinister_strike', 'eviscerate', 'backstab', 'gouge', 'evasion', 'slice_and_dice', 'sprint', 'kidney_shot', 'ambush', 'adrenaline_rush'],
    color: 0xfff569,
    crest: '⚷',
  },
  paladin: {
    id: 'paladin',
    name: 'Paladin',
    baseStats: { str: 22, agi: 17, sta: 22, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 1, spi: 1, armor: 12 },
    baseHp: 55,
    hpPerLevel: 17,
    baseMana: 80,
    manaPerLevel: 20,
    resourceType: 'mana',
    startWeapon: 'training_mace',
    startChest: 'recruit_tunic',
    abilities: ['seal_of_righteousness', 'holy_light', 'devotion_aura', 'judgement', 'blessing_of_might', 'divine_protection', 'hammer_of_justice', 'lay_on_hands', 'flash_of_light', 'exorcism', 'consecration'],
    color: 0xf58cba,
    crest: '🔨',
  },
  hunter: {
    id: 'hunter',
    name: 'Avcı',
    baseStats: { str: 14, agi: 25, sta: 19, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 1, agi: 3, sta: 2, int: 1, spi: 1, armor: 8 },
    baseHp: 50,
    hpPerLevel: 15,
    baseMana: 80,
    manaPerLevel: 18,
    resourceType: 'mana',
    startWeapon: 'rusty_hatchet',
    startChest: 'footpad_jerkin',
    ranged: { min: 5, max: 9, speed: 2.3, maxRange: 35, minRange: 8 },
    abilities: ['raptor_strike', 'aspect_of_the_hawk', 'serpent_sting', 'arcane_shot', 'concussive_shot', 'mongoose_bite', 'wing_clip', 'aspect_of_the_cheetah', 'aimed_shot', 'rapid_fire'],
    color: 0xabd473,
    crest: '🏹',
  },
  priest: {
    id: 'priest',
    name: 'Hoca',
    baseStats: { str: 10, agi: 11, sta: 13, int: 22, spi: 24, armor: 20 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 2, spi: 3, armor: 4 },
    baseHp: 38,
    hpPerLevel: 11,
    baseMana: 110,
    manaPerLevel: 26,
    resourceType: 'mana',
    startWeapon: 'gnarled_staff',
    startChest: 'apprentice_robe',
    abilities: ['smite', 'lesser_heal', 'power_word_fortitude', 'shadow_word_pain', 'power_word_shield', 'renew', 'mind_blast', 'heal', 'mind_flay', 'flash_heal'],
    color: 0xfffff0,
    crest: '☪',
  },
  shaman: {
    id: 'shaman',
    name: 'Şaman',
    baseStats: { str: 18, agi: 16, sta: 20, int: 18, spi: 18, armor: 40 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 10 },
    baseHp: 48,
    hpPerLevel: 15,
    baseMana: 90,
    manaPerLevel: 22,
    resourceType: 'mana',
    startWeapon: 'training_mace',
    startChest: 'footpad_jerkin',
    abilities: ['lightning_bolt', 'rockbiter_weapon', 'healing_wave', 'earth_shock', 'lightning_shield', 'flame_shock', 'frost_shock', 'ghost_wolf', 'stormstrike'],
    color: 0x0070de,
    crest: '🌩',
  },
  warlock: {
    id: 'warlock',
    name: 'Kara Büyücü',
    baseStats: { str: 11, agi: 12, sta: 15, int: 21, spi: 21, armor: 22 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    baseHp: 42,
    hpPerLevel: 12,
    baseMana: 105,
    manaPerLevel: 25,
    resourceType: 'mana',
    startWeapon: 'gnarled_staff',
    startChest: 'apprentice_robe',
    abilities: ['shadow_bolt', 'demon_skin', 'immolate', 'corruption', 'life_tap', 'curse_of_agony', 'drain_life', 'fear', 'searing_pain', 'shadowburn'],
    color: 0x9482c9,
    crest: '🕯',
  },
  druid: {
    id: 'druid',
    name: 'Druid',
    baseStats: { str: 15, agi: 15, sta: 17, int: 19, spi: 20, armor: 30 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 6 },
    baseHp: 45,
    hpPerLevel: 13,
    baseMana: 95,
    manaPerLevel: 22,
    resourceType: 'mana',
    startWeapon: 'gnarled_staff',
    startChest: 'footpad_jerkin',
    abilities: ['wrath', 'healing_touch', 'mark_of_the_wild', 'moonfire', 'rejuvenation', 'thorns', 'entangling_roots', 'bear_form', 'regrowth', 'barkskin', 'starfire'],
    color: 0xff7d0a,
    crest: '🐻',
  },
};

// ---------------------------------------------------------------------------
// Abilities — rank values and learn levels from vanilla (levels 1-10)
// ---------------------------------------------------------------------------

export const ABILITIES: Record<string, AbilityDef> = {
  // ====================== WARRIOR ======================
  heroic_strike: {
    id: 'heroic_strike', name: 'Kahramanca Vuruş', class: 'warrior', learnLevel: 1,
    cost: 15, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, onNextSwing: true, offGcd: true,
    effects: [{ type: 'weaponDamage', bonus: 11 }],
    ranks: [
      { rank: 2, level: 8, cost: 15, effects: [{ type: 'weaponDamage', bonus: 21 }] },
      { rank: 3, level: 14, cost: 15, effects: [{ type: 'weaponDamage', bonus: 32 }] },
      { rank: 4, level: 20, cost: 15, effects: [{ type: 'weaponDamage', bonus: 44 }] },
    ],
    icon: 'HS', iconColor: '#c0392b',
    description: 'Yakın dövüş hasarını $d artıran güçlü bir saldırı. Bir sonraki savuruşunda etkinleşir.',
  },
  battle_shout: {
    id: 'battle_shout', name: 'Savaş Narası', class: 'warrior', learnLevel: 1,
    cost: 10, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 20, duration: 120 }],
    ranks: [
      { rank: 2, level: 12, cost: 10, effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 35, duration: 120 }] },
      { rank: 3, level: 20, cost: 10, effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 50, duration: 120 }] },
    ],
    icon: 'BS', iconColor: '#e67e22',
    description: 'Saldırı gücünü 2 dakika boyunca 20 artırır.',
  },
  charge: {
    id: 'charge', name: 'Hücum', class: 'warrior', learnLevel: 4,
    cost: 0, castTime: 0, cooldown: 15, range: 25, minRange: 8, school: 'physical',
    requiresTarget: true, offGcd: true,
    effects: [{ type: 'charge' }, { type: 'stun', duration: 1 }],
    icon: 'CH', iconColor: '#d35400',
    description: 'Bir düşmana hücum eder, 9 öfke üretir ve onu 1 saniye sersemletir. 8-25 metre menzil.',
  },
  rend: {
    id: 'rend', name: 'Yarma', class: 'warrior', learnLevel: 4,
    cost: 10, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 15, duration: 9, interval: 3 }],
    ranks: [
      { rank: 2, level: 10, cost: 10, effects: [{ type: 'dot', total: 21, duration: 9, interval: 3 }] },
      { rank: 3, level: 16, cost: 10, effects: [{ type: 'dot', total: 36, duration: 12, interval: 3 }] },
    ],
    icon: 'RE', iconColor: '#922b21',
    description: 'Hedefi yaralar; 9 saniye boyunca toplam $d kanama hasarı verir.',
  },
  thunder_clap: {
    id: 'thunder_clap', name: 'Gök Gürültüsü', class: 'warrior', learnLevel: 6,
    cost: 20, castTime: 0, cooldown: 4, range: 0, school: 'physical',
    requiresTarget: false,
    effects: [
      { type: 'aoeDamage', min: 12, max: 14, radius: 8 },
      { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
    ],
    ranks: [
      {
        rank: 2, level: 14, cost: 20,
        effects: [
          { type: 'aoeDamage', min: 23, max: 27, radius: 8 },
          { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
        ],
      },
      {
        rank: 3, level: 20, cost: 20,
        effects: [
          { type: 'aoeDamage', min: 37, max: 43, radius: 8 },
          { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
        ],
      },
    ],
    icon: 'TC', iconColor: '#2980b9',
    description: 'Yakındaki düşmanlara $d hasar verir ve saldırı hızlarını 10 saniye boyunca %10 yavaşlatır.',
  },
  hamstring: {
    id: 'hamstring', name: 'Diz Kesme', class: 'warrior', learnLevel: 8,
    cost: 10, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 5, max: 5 }, { type: 'slow', mult: 0.5, duration: 15 }],
    ranks: [{
      rank: 2, level: 16, cost: 10,
      effects: [{ type: 'directDamage', min: 12, max: 12 }, { type: 'slow', mult: 0.5, duration: 15 }],
    }],
    icon: 'HA', iconColor: '#a93226',
    description: 'Düşmanı 5 hasarla sakatlar; hareket hızını 15 saniye boyunca %50 yavaşlatır.',
  },
  bloodrage: {
    id: 'bloodrage', name: 'Kan Öfkesi', class: 'warrior', learnLevel: 10,
    cost: 0, castTime: 0, cooldown: 60, range: 0, school: 'physical',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'selfDamagePctMax', pct: 0.08 }, { type: 'gainResource', amount: 10 }],
    icon: 'BR', iconColor: '#e74c3c',
    description: 'Can karşılığında 10 öfke üretir.',
  },
  overpower: {
    id: 'overpower', name: 'Alt Etme', class: 'warrior', learnLevel: 10,
    cost: 5, castTime: 0, cooldown: 5, range: 0, school: 'physical',
    requiresTarget: true, requiresDodgeProc: true,
    effects: [{ type: 'weaponStrike', bonus: 5, cannotBeDodged: true }],
    ranks: [{ rank: 2, level: 16, cost: 5, effects: [{ type: 'weaponStrike', bonus: 15, cannotBeDodged: true }] }],
    icon: 'OP', iconColor: '#f39c12',
    description: 'Silah hasarı +5 anlık saldırı. Yalnızca hedef savuşturduktan sonra kullanılabilir. Savuşturulamaz.',
  },
  execute: {
    id: 'execute', name: 'İnfaz', class: 'warrior', learnLevel: 14,
    cost: 15, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, requiresTargetHpBelow: 0.2,
    effects: [{ type: 'directDamage', min: 60, max: 75 }],
    icon: 'EX', iconColor: '#7b241c',
    description: 'Yaralı bir düşmanın işini bitirmeye çalışır; $d hasar verir. Yalnızca canı %20\'nin altındaki düşmanlarda kullanılabilir.',
  },
  slam: {
    id: 'slam', name: 'Çarpma', class: 'warrior', learnLevel: 16,
    cost: 15, castTime: 1.5, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 25 }],
    icon: 'SL', iconColor: '#b9770e',
    description: 'Rakibe silah hasarı artı $d ile çarpar.',
  },
  cleave: {
    id: 'cleave', name: 'Biçme', class: 'warrior', learnLevel: 18,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 20, max: 26, radius: 5 }],
    icon: 'CL', iconColor: '#cb4335',
    description: 'Önündeki tüm düşmanlara $d hasar veren süpürücü bir vuruş.',
  },

  // ====================== MAGE ======================
  fireball: {
    id: 'fireball', name: 'Ateş Topu', class: 'mage', learnLevel: 1,
    cost: 30, castTime: 1.5, cooldown: 0, range: 30, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 16, max: 25 }, { type: 'dot', total: 2, duration: 4, interval: 2 }],
    ranks: [{
      rank: 2, level: 6, cost: 45, castTime: 2.0,
      effects: [{ type: 'directDamage', min: 22, max: 31 }, { type: 'dot', total: 3, duration: 6, interval: 2 }],
    }, {
      rank: 3, level: 12, cost: 65, castTime: 2.5,
      effects: [{ type: 'directDamage', min: 36, max: 48 }, { type: 'dot', total: 6, duration: 6, interval: 2 }],
    }, {
      rank: 4, level: 18, cost: 95, castTime: 3.0,
      effects: [{ type: 'directDamage', min: 58, max: 78 }, { type: 'dot', total: 12, duration: 8, interval: 2 }],
    }],
    icon: 'FB', iconColor: '#e74c3c',
    description: 'Alevden bir top fırlatır; $d Ateş hasarı artı zamanla ek hasar verir.',
  },
  frost_armor: {
    id: 'frost_armor', name: 'Buz Zırhı', class: 'mage', learnLevel: 1,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'frost',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 30, duration: 1800 }],
    ranks: [
      { rank: 2, level: 10, cost: 30, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 50, duration: 1800 }] },
      { rank: 3, level: 18, cost: 45, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 70, duration: 1800 }] },
    ],
    icon: 'FA', iconColor: '#aed6f1',
    description: 'Seni buzla kaplar; zırhını 30 dakika boyunca 30 artırır.',
  },
  arcane_intellect: {
    id: 'arcane_intellect', name: 'Arkana Zekâsı', class: 'mage', learnLevel: 1,
    cost: 25, castTime: 0, cooldown: 0, range: 0, school: 'arcane',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_int', value: 2, duration: 1800 }],
    ranks: [{ rank: 2, level: 14, cost: 60, effects: [{ type: 'selfBuff', kind: 'buff_int', value: 7, duration: 1800 }] }],
    icon: 'AI', iconColor: '#bb8fce',
    description: 'Zekâyı 30 dakika boyunca 2 artırır.',
  },
  frostbolt: {
    id: 'frostbolt', name: 'Buz Oku', class: 'mage', learnLevel: 4,
    cost: 25, castTime: 1.5, cooldown: 0, range: 30, school: 'frost',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 18, max: 20 }, { type: 'slow', mult: 0.6, duration: 5 }],
    ranks: [{
      rank: 2, level: 8, cost: 35, castTime: 2.0,
      effects: [{ type: 'directDamage', min: 31, max: 35 }, { type: 'slow', mult: 0.6, duration: 6 }],
    }, {
      rank: 3, level: 14, cost: 50, castTime: 2.5,
      effects: [{ type: 'directDamage', min: 44, max: 50 }, { type: 'slow', mult: 0.6, duration: 7 }],
    }, {
      rank: 4, level: 20, cost: 70, castTime: 2.5,
      effects: [{ type: 'directDamage', min: 66, max: 74 }, { type: 'slow', mult: 0.6, duration: 9 }],
    }],
    icon: 'FR', iconColor: '#3498db',
    description: 'Bir buz oku fırlatır; $d Buz hasarı verir ve hareketi %40 yavaşlatır.',
  },
  conjure_water: {
    id: 'conjure_water', name: 'Su Yaratma', class: 'mage', learnLevel: 4,
    cost: 40, castTime: 3, cooldown: 0, range: 0, school: 'arcane',
    requiresTarget: false,
    effects: [], // special-cased: creates conjured_water{rank} in bags
    ranks: [
      { rank: 2, level: 10, cost: 70, effects: [] },
      { rank: 3, level: 16, cost: 110, effects: [] },
    ],
    icon: 'CW', iconColor: '#5dade2',
    description: '2 şişe su yaratır; içildiğinde mana yeniler. Yüksek kademeler daha saf su yaratır.',
  },
  fire_blast: {
    id: 'fire_blast', name: 'Ateş Patlaması', class: 'mage', learnLevel: 6,
    cost: 40, castTime: 0, cooldown: 8, range: 20, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 27, max: 35 }],
    ranks: [
      { rank: 2, level: 12, cost: 60, effects: [{ type: 'directDamage', min: 44, max: 54 }] },
      { rank: 3, level: 18, cost: 85, effects: [{ type: 'directDamage', min: 68, max: 82 }] },
    ],
    icon: 'BL', iconColor: '#e67e22',
    description: 'Düşmana $d Ateş hasarı verir. Anlık.',
  },
  arcane_missiles: {
    id: 'arcane_missiles', name: 'Arkana Füzeleri', class: 'mage', learnLevel: 8,
    cost: 50, castTime: 0, channel: { duration: 3, ticks: 3 }, cooldown: 0, range: 30, school: 'arcane',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 8, max: 8 }], // per missile
    ranks: [
      { rank: 2, level: 14, cost: 75, effects: [{ type: 'directDamage', min: 14, max: 14 }] },
      { rank: 3, level: 20, cost: 105, effects: [{ type: 'directDamage', min: 22, max: 22 }] },
    ],
    icon: 'AM', iconColor: '#c39bd3',
    description: 'Düşmana Arkana Füzeleri fırlatır; 3 saniye boyunca saniyede 8 Arkana hasarı verir.',
  },
  polymorph: {
    id: 'polymorph', name: 'Şekil Değiştirme', class: 'mage', learnLevel: 8,
    cost: 50, castTime: 1.5, cooldown: 0, range: 30, school: 'arcane',
    requiresTarget: true,
    effects: [{ type: 'polymorph', duration: 15 }],
    ranks: [{ rank: 2, level: 18, cost: 70, effects: [{ type: 'polymorph', duration: 20 }] }],
    icon: 'PM', iconColor: '#f5b7b1',
    description: 'Düşmanı 15 saniyeye kadar koyuna çevirir. Koyun başıboş dolanır ve hızla iyileşir. Her türlü hasar etkiyi bozar. Yalnızca hayvanlar ve insansılar.',
  },
  frost_nova: {
    id: 'frost_nova', name: 'Buz Novası', class: 'mage', learnLevel: 10,
    cost: 35, castTime: 0, cooldown: 22, range: 0, school: 'frost',
    requiresTarget: false,
    effects: [{ type: 'aoeRoot', duration: 8, radius: 10, min: 6, max: 7 }],
    ranks: [{ rank: 2, level: 16, cost: 50, effects: [{ type: 'aoeRoot', duration: 8, radius: 10, min: 12, max: 14 }] }],
    icon: 'NV', iconColor: '#85c1e9',
    description: 'Yakındaki tüm düşmanları 8 saniyeye kadar yerinde dondurur ve $d Buz hasarı verir.',
  },
  arcane_explosion: {
    id: 'arcane_explosion', name: 'Arkana Patlaması', class: 'mage', learnLevel: 14,
    cost: 60, castTime: 0, cooldown: 0, range: 0, school: 'arcane',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 26, max: 31, radius: 10 }],
    icon: 'AE', iconColor: '#af7ac5',
    description: 'Bir Arkana enerjisi patlaması, yakındaki tüm düşmanlara $d Arkana hasarı verir.',
  },
  scorch: {
    id: 'scorch', name: 'Kavurma', class: 'mage', learnLevel: 16,
    cost: 35, castTime: 1.5, cooldown: 0, range: 30, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 32, max: 40 }],
    icon: 'SC', iconColor: '#dc7633',
    description: 'Düşmanı $d Ateş hasarıyla kavurur. Hızlı okunur.',
  },
  ice_barrier: {
    id: 'ice_barrier', name: 'Buz Bariyeri', class: 'mage', learnLevel: 20,
    cost: 90, castTime: 0, cooldown: 30, range: 0, school: 'frost',
    requiresTarget: false,
    effects: [{ type: 'absorb', amount: 130, duration: 60 }],
    icon: 'IB', iconColor: '#d6eaf8',
    description: 'Seni buzla kalkanlar; 60 saniye boyunca 130 hasar emer.',
  },

  // ====================== ROGUE ======================
  sinister_strike: {
    id: 'sinister_strike', name: 'Sinsi Vuruş', class: 'rogue', learnLevel: 1,
    cost: 45, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, awardsCombo: 1,
    effects: [{ type: 'weaponStrike', bonus: 3 }],
    ranks: [
      { rank: 2, level: 8, cost: 45, effects: [{ type: 'weaponStrike', bonus: 6 }] },
      { rank: 3, level: 14, cost: 45, effects: [{ type: 'weaponStrike', bonus: 12 }] },
      { rank: 4, level: 20, cost: 45, effects: [{ type: 'weaponStrike', bonus: 18 }] },
    ],
    icon: 'SS', iconColor: '#f4d03f',
    description: 'Silah hasarı artı $d anlık vuruş. 1 kombo puanı kazandırır.',
  },
  eviscerate: {
    id: 'eviscerate', name: 'Deşme', class: 'rogue', learnLevel: 1,
    cost: 35, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, spendsCombo: true,
    effects: [{ type: 'finisherDamage', base: 4, perCombo: 7, variance: 4 }],
    ranks: [
      { rank: 2, level: 12, cost: 35, effects: [{ type: 'finisherDamage', base: 8, perCombo: 12, variance: 6 }] },
      { rank: 3, level: 18, cost: 35, effects: [{ type: 'finisherDamage', base: 14, perCombo: 18, variance: 9 }] },
    ],
    icon: 'EV', iconColor: '#cb4335',
    description: 'Kombo puanı başına hasar veren bitirici hamle.',
  },
  backstab: {
    id: 'backstab', name: 'Sırttan Bıçaklama', class: 'rogue', learnLevel: 4,
    cost: 60, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, awardsCombo: 1,
    effects: [{ type: 'weaponStrike', bonus: 11, requiresBehind: true, weaponMult: 1.5 }],
    ranks: [
      { rank: 2, level: 12, cost: 60, effects: [{ type: 'weaponStrike', bonus: 20, requiresBehind: true, weaponMult: 1.5 }] },
      { rank: 3, level: 18, cost: 60, effects: [{ type: 'weaponStrike', bonus: 32, requiresBehind: true, weaponMult: 1.5 }] },
    ],
    icon: 'BK', iconColor: '#ec7063',
    description: 'Hedefi %150 silah hasarı artı $d ile sırtından bıçaklar. Hedefin arkasında olmak gerekir. Hançer gerektirir. 1 kombo puanı kazandırır.',
  },
  gouge: {
    id: 'gouge', name: 'Göz Oyma', class: 'rogue', learnLevel: 6,
    cost: 45, castTime: 0, cooldown: 10, range: 0, school: 'physical',
    requiresTarget: true, awardsCombo: 1,
    effects: [{ type: 'directDamage', min: 8, max: 9 }, { type: 'incapacitate', duration: 4 }],
    ranks: [{
      rank: 2, level: 14, cost: 45,
      effects: [{ type: 'directDamage', min: 15, max: 17 }, { type: 'incapacitate', duration: 4 }],
    }],
    icon: 'GO', iconColor: '#d98880',
    description: 'Hedefe vurur ve onu 4 saniye etkisiz bırakır. Her türlü hasar etkiyi bozar. 1 kombo puanı kazandırır.',
  },
  evasion: {
    id: 'evasion', name: 'Savuşturma', class: 'rogue', learnLevel: 8,
    cost: 0, castTime: 0, cooldown: 300, range: 0, school: 'physical',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_dodge', value: 0.5, duration: 15 }],
    icon: 'EA', iconColor: '#82e0aa',
    description: 'Savuşturma şansını 15 saniye boyunca %50 artırır.',
  },
  slice_and_dice: {
    id: 'slice_and_dice', name: 'Doğra ve Parçala', class: 'rogue', learnLevel: 10,
    cost: 25, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, spendsCombo: true,
    effects: [{ type: 'finisherHaste', mult: 1.3, basedur: 9, perCombo: 3 }],
    icon: 'SD', iconColor: '#f7dc6f',
    description: 'Yakın dövüş saldırı hızını %30 artıran bitirici hamle. Kombo puanı başına daha uzun sürer.',
  },
  sprint: {
    id: 'sprint', name: 'Koşu', class: 'rogue', learnLevel: 10,
    cost: 0, castTime: 0, cooldown: 300, range: 0, school: 'physical',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.7, duration: 15 }],
    icon: 'SP', iconColor: '#aab7b8',
    description: 'Hareket hızını 15 saniye boyunca %70 artırır.',
  },
  kidney_shot: {
    id: 'kidney_shot', name: 'Böbrek Darbesi', class: 'rogue', learnLevel: 14,
    cost: 25, castTime: 0, cooldown: 20, range: 0, school: 'physical',
    requiresTarget: true, spendsCombo: true,
    effects: [{ type: 'finisherStun', base: 1, perCombo: 1 }],
    icon: 'KS', iconColor: '#e59866',
    description: 'Hedefi sersemleten bitirici hamle. Kombo puanı başına 1 saniye daha uzun sürer.',
  },
  ambush: {
    id: 'ambush', name: 'Pusu', class: 'rogue', learnLevel: 16,
    cost: 60, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true, awardsCombo: 1,
    effects: [{ type: 'weaponStrike', bonus: 28, requiresBehind: true, weaponMult: 2.5 }],
    icon: 'AB', iconColor: '#935116',
    description: 'Hedefe %250 silah hasarı artı $d ile pusu kurar. Hedefin arkasında olmak gerekir. Hançer gerektirir. 1 kombo puanı kazandırır.',
  },
  adrenaline_rush: {
    id: 'adrenaline_rush', name: 'Adrenalin Patlaması', class: 'rogue', learnLevel: 20,
    cost: 0, castTime: 0, cooldown: 180, range: 0, school: 'physical',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'gainResource', amount: 60 }],
    icon: 'AR', iconColor: '#f5b041',
    description: 'Kanın kaynar; anında 60 enerji yeniler.',
  },

  // ====================== PALADIN ======================
  seal_of_righteousness: {
    id: 'seal_of_righteousness', name: 'Doğruluk Mührü', class: 'paladin', learnLevel: 1,
    cost: 25, castTime: 0, cooldown: 0, range: 0, school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'imbue', bonus: 4, duration: 30, judgeMin: 10, judgeMax: 18 }],
    ranks: [
      { rank: 2, level: 10, cost: 35, effects: [{ type: 'imbue', bonus: 7, duration: 30, judgeMin: 18, judgeMax: 28 }] },
      { rank: 3, level: 16, cost: 50, effects: [{ type: 'imbue', bonus: 11, duration: 30, judgeMin: 30, judgeMax: 44 }] },
    ],
    icon: 'SR', iconColor: '#f9e79f',
    description: 'Seni 30 saniye boyunca Kutsal güçle doldurur; her yakın dövüş savuruşun 4 ek Kutsal hasar verir. Hüküm ile serbest bırak.',
  },
  holy_light: {
    id: 'holy_light', name: 'Kutsal Işık', class: 'paladin', learnLevel: 1,
    cost: 35, castTime: 2.5, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 42, max: 51 }],
    ranks: [
      { rank: 2, level: 8, cost: 60, effects: [{ type: 'heal', min: 76, max: 90 }] },
      { rank: 3, level: 14, cost: 95, effects: [{ type: 'heal', min: 122, max: 144 }] },
      { rank: 4, level: 20, cost: 140, effects: [{ type: 'heal', min: 190, max: 222 }] },
    ],
    icon: 'HL', iconColor: '#fdf2c7',
    description: 'Dost bir hedefi $d kadar iyileştirir.',
  },
  devotion_aura: {
    id: 'devotion_aura', name: 'Adanmışlık Aurası', class: 'paladin', learnLevel: 1,
    cost: 0, castTime: 0, cooldown: 0, range: 0, school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 40, duration: 1800 }],
    ranks: [
      { rank: 2, level: 12, cost: 0, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 75, duration: 1800 }] },
      { rank: 3, level: 18, cost: 0, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 110, duration: 1800 }] },
    ],
    icon: 'DA', iconColor: '#f4d03f',
    description: 'Zırhını 30 dakika boyunca 40 artırır.',
  },
  judgement: {
    id: 'judgement', name: 'Hüküm', class: 'paladin', learnLevel: 4,
    cost: 30, castTime: 0, cooldown: 10, range: 10, school: 'holy',
    requiresTarget: true,
    effects: [{ type: 'judgement' }],
    icon: 'JD', iconColor: '#f5b041',
    description: 'Etkin Mührünü düşmanın üzerine salar; mührü tüketerek hüküm hasarını verir.',
  },
  blessing_of_might: {
    id: 'blessing_of_might', name: 'Kudret Kutsaması', class: 'paladin', learnLevel: 4,
    cost: 25, castTime: 0, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'buff_ap', value: 15, duration: 300 }],
    ranks: [
      { rank: 2, level: 12, cost: 40, effects: [{ type: 'buffTarget', kind: 'buff_ap', value: 30, duration: 300 }] },
      { rank: 3, level: 20, cost: 60, effects: [{ type: 'buffTarget', kind: 'buff_ap', value: 45, duration: 300 }] },
    ],
    icon: 'BM', iconColor: '#f8c471',
    description: 'Dost bir hedefe Kutsama yerleştirir; saldırı gücünü 5 dakika boyunca 15 artırır.',
  },
  divine_protection: {
    id: 'divine_protection', name: 'İlahi Koruma', class: 'paladin', learnLevel: 6,
    cost: 15, castTime: 0, cooldown: 180, range: 0, school: 'holy',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'absorb', amount: 50, duration: 10 }],
    ranks: [{ rank: 2, level: 14, cost: 25, effects: [{ type: 'absorb', amount: 110, duration: 10 }] }],
    icon: 'DP', iconColor: '#fcf3cf',
    description: 'Kutsal bir kalkan 10 saniye boyunca 50 hasar emer.',
  },
  hammer_of_justice: {
    id: 'hammer_of_justice', name: 'Adalet Çekici', class: 'paladin', learnLevel: 8,
    cost: 30, castTime: 0, cooldown: 60, range: 10, school: 'holy',
    requiresTarget: true,
    effects: [{ type: 'stun', duration: 3 }],
    ranks: [{ rank: 2, level: 16, cost: 45, effects: [{ type: 'stun', duration: 4 }] }],
    icon: 'HJ', iconColor: '#d4ac0d',
    description: 'Hedefi 3 saniye sersemletir.',
  },
  lay_on_hands: {
    id: 'lay_on_hands', name: 'El Verme', class: 'paladin', learnLevel: 10,
    cost: 0, castTime: 0, cooldown: 600, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 250, max: 250 }],
    ranks: [{ rank: 2, level: 18, cost: 0, effects: [{ type: 'heal', min: 600, max: 600 }] }],
    icon: 'LH', iconColor: '#fef9e7',
    description: 'Devasa bir iyileştirme dalgası: 250 can yeniler. 10 dakika bekleme süresi.',
  },
  flash_of_light: {
    id: 'flash_of_light', name: 'Işık Parıltısı', class: 'paladin', learnLevel: 12,
    cost: 35, castTime: 1.5, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 62, max: 76 }],
    icon: 'FL', iconColor: '#fcf3cf',
    description: 'Dost bir hedefi $d kadar iyileştiren hızlı ve verimli bir Işık parıltısı.',
  },
  exorcism: {
    id: 'exorcism', name: 'Şeytan Çıkarma', class: 'paladin', learnLevel: 14,
    cost: 55, castTime: 0, cooldown: 15, range: 30, school: 'holy',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 46, max: 56 }],
    icon: 'EX', iconColor: '#f7dc6f',
    description: 'Kötüleri Kutsal gazapla kovar; $d Kutsal hasar verir.',
  },
  consecration: {
    id: 'consecration', name: 'Takdis', class: 'paladin', learnLevel: 18,
    cost: 60, castTime: 0, cooldown: 8, range: 0, school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 28, max: 34, radius: 8 }],
    icon: 'CN', iconColor: '#f9e79f',
    description: 'Altındaki toprağı kutsar; yakındaki düşmanları $d Kutsal hasarla dağlar.',
  },

  // ====================== HUNTER ======================
  raptor_strike: {
    id: 'raptor_strike', name: 'Yırtıcı Vuruşu', class: 'hunter', learnLevel: 1,
    cost: 15, castTime: 0, cooldown: 6, range: 0, school: 'physical',
    requiresTarget: true, onNextSwing: true, offGcd: true,
    effects: [{ type: 'weaponDamage', bonus: 5 }],
    ranks: [
      { rank: 2, level: 8, cost: 25, effects: [{ type: 'weaponDamage', bonus: 11 }] },
      { rank: 3, level: 14, cost: 35, effects: [{ type: 'weaponDamage', bonus: 18 }] },
      { rank: 4, level: 20, cost: 45, effects: [{ type: 'weaponDamage', bonus: 27 }] },
    ],
    icon: 'RS', iconColor: '#a9dfbf',
    description: 'Hasarı 5 artıran güçlü bir yakın dövüş saldırısı. Bir sonraki savuruşunda etkinleşir.',
  },
  aspect_of_the_hawk: {
    id: 'aspect_of_the_hawk', name: 'Şahin Sureti', class: 'hunter', learnLevel: 4,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 20, duration: 1800 }],
    ranks: [
      { rank: 2, level: 12, cost: 30, effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 35, duration: 1800 }] },
      { rank: 3, level: 18, cost: 40, effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 50, duration: 1800 }] },
    ],
    icon: 'AH', iconColor: '#7dcea0',
    description: 'Şahin suretine bürünürsün; saldırı gücünü 30 dakika boyunca 20 artırır.',
  },
  serpent_sting: {
    id: 'serpent_sting', name: 'Yılan Sokması', class: 'hunter', learnLevel: 4,
    cost: 15, castTime: 0, cooldown: 0, range: 35, minRange: 8, school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 20, duration: 15, interval: 3 }],
    ranks: [
      { rank: 2, level: 10, cost: 25, effects: [{ type: 'dot', total: 35, duration: 15, interval: 3 }] },
      { rank: 3, level: 16, cost: 35, effects: [{ type: 'dot', total: 55, duration: 15, interval: 3 }] },
    ],
    icon: 'SS', iconColor: '#58d68d',
    description: 'Hedefi sokar; 15 saniye boyunca $d Doğa hasarı verir.',
  },
  arcane_shot: {
    id: 'arcane_shot', name: 'Arkana Atışı', class: 'hunter', learnLevel: 6,
    cost: 25, castTime: 0, cooldown: 6, range: 35, minRange: 8, school: 'arcane',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 13, max: 17 }],
    ranks: [
      { rank: 2, level: 12, cost: 40, effects: [{ type: 'directDamage', min: 24, max: 30 }] },
      { rank: 3, level: 18, cost: 55, effects: [{ type: 'directDamage', min: 38, max: 47 }] },
    ],
    icon: 'AS', iconColor: '#bb8fce',
    description: '$d Arkana hasarı veren anlık bir atış.',
  },
  concussive_shot: {
    id: 'concussive_shot', name: 'Sersemletici Atış', class: 'hunter', learnLevel: 8,
    cost: 20, castTime: 0, cooldown: 12, range: 35, minRange: 8, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 4, max: 6 }, { type: 'slow', mult: 0.5, duration: 4 }],
    icon: 'CS', iconColor: '#85c1e9',
    description: 'Hedefi sersemletir; hareketi 4 saniye boyunca %50 yavaşlatır.',
  },
  mongoose_bite: {
    id: 'mongoose_bite', name: 'Firavun Faresi Isırığı', class: 'hunter', learnLevel: 10,
    cost: 10, castTime: 0, cooldown: 5, range: 0, school: 'physical',
    requiresTarget: true, requiresDodgeProc: true,
    effects: [{ type: 'weaponStrike', bonus: 12, cannotBeDodged: true }],
    ranks: [{ rank: 2, level: 16, cost: 10, effects: [{ type: 'weaponStrike', bonus: 24, cannotBeDodged: true }] }],
    icon: 'MB', iconColor: '#52be80',
    description: 'Hedef savuşturduktan sonra silah hasarı artı 12 ile karşı saldırı. Savuşturulamaz.',
  },
  wing_clip: {
    id: 'wing_clip', name: 'Kanat Kırpma', class: 'hunter', learnLevel: 10,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 3, max: 5 }, { type: 'slow', mult: 0.6, duration: 10 }],
    icon: 'WC', iconColor: '#a3e4d7',
    description: 'Düşmanı 10 saniye boyunca %40 yavaşlatan bir yara açar.',
  },
  aspect_of_the_cheetah: {
    id: 'aspect_of_the_cheetah', name: 'Çita Sureti', class: 'hunter', learnLevel: 14,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.3, duration: 1800 }],
    icon: 'AC', iconColor: '#f8c471',
    description: 'Çita suretine bürünürsün; hareket hızını 30 dakika boyunca %30 artırır.',
  },
  aimed_shot: {
    id: 'aimed_shot', name: 'Nişanlı Atış', class: 'hunter', learnLevel: 16,
    cost: 50, castTime: 3.0, cooldown: 6, range: 35, minRange: 8, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 50, max: 62 }],
    icon: 'AI', iconColor: '#d35400',
    description: '$d hasar veren özenle nişan alınmış bir atış.',
  },
  rapid_fire: {
    id: 'rapid_fire', name: 'Seri Atış', class: 'hunter', learnLevel: 20,
    cost: 0, castTime: 0, cooldown: 300, range: 0, school: 'physical',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_haste', value: 1.4, duration: 15 }],
    icon: 'RF', iconColor: '#ec7063',
    description: 'Saldırı hızını 15 saniye boyunca %40 artırır.',
  },

  // ====================== PRIEST ======================
  smite: {
    id: 'smite', name: 'Çarpma Duası', class: 'priest', learnLevel: 1,
    cost: 20, castTime: 2.0, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 15, max: 20 }],
    ranks: [
      { rank: 2, level: 8, cost: 32, effects: [{ type: 'directDamage', min: 26, max: 33 }] },
      { rank: 3, level: 14, cost: 48, castTime: 2.5, effects: [{ type: 'directDamage', min: 42, max: 52 }] },
      { rank: 4, level: 20, cost: 70, castTime: 2.5, effects: [{ type: 'directDamage', min: 64, max: 78 }] },
    ],
    icon: 'SM', iconColor: '#fdf2c7',
    description: 'Düşmanı $d Kutsal hasarla çarpar.',
  },
  lesser_heal: {
    id: 'lesser_heal', name: 'Küçük İyileştirme', class: 'priest', learnLevel: 1,
    cost: 30, castTime: 2.0, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 47, max: 58 }],
    ranks: [
      { rank: 2, level: 6, cost: 45, effects: [{ type: 'heal', min: 72, max: 86 }] },
      { rank: 3, level: 12, cost: 65, effects: [{ type: 'heal', min: 110, max: 132 }] },
    ],
    icon: 'LH', iconColor: '#fef9e7',
    description: 'Dost bir hedefi $d kadar iyileştirir.',
  },
  power_word_fortitude: {
    id: 'power_word_fortitude', name: 'Kudret Sözü: Metanet', class: 'priest', learnLevel: 1,
    cost: 30, castTime: 0, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'buff_sta', value: 3, duration: 1800 }],
    ranks: [
      { rank: 2, level: 12, cost: 55, effects: [{ type: 'buffTarget', kind: 'buff_sta', value: 7, duration: 1800 }] },
      { rank: 3, level: 20, cost: 80, effects: [{ type: 'buffTarget', kind: 'buff_sta', value: 12, duration: 1800 }] },
    ],
    icon: 'PF', iconColor: '#fff',
    description: 'Hedefin Dayanıklılığını 30 dakika boyunca 3 artırır.',
  },
  shadow_word_pain: {
    id: 'shadow_word_pain', name: 'Gölge Sözü: Acı', class: 'priest', learnLevel: 4,
    cost: 25, castTime: 0, cooldown: 0, range: 30, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 30, duration: 18, interval: 3 }],
    ranks: [
      { rank: 2, level: 10, cost: 38, effects: [{ type: 'dot', total: 54, duration: 18, interval: 3 }] },
      { rank: 3, level: 16, cost: 55, effects: [{ type: 'dot', total: 84, duration: 18, interval: 3 }] },
    ],
    icon: 'SW', iconColor: '#9b59b6',
    description: 'Bir karanlık sözü, 18 saniye boyunca $d Gölge hasarı verir.',
  },
  power_word_shield: {
    id: 'power_word_shield', name: 'Kudret Sözü: Kalkan', class: 'priest', learnLevel: 6,
    cost: 45, castTime: 0, cooldown: 6, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'absorb', amount: 48, duration: 30 }],
    ranks: [
      { rank: 2, level: 12, cost: 70, effects: [{ type: 'absorb', amount: 90, duration: 30 }] },
      { rank: 3, level: 18, cost: 100, effects: [{ type: 'absorb', amount: 145, duration: 30 }] },
    ],
    icon: 'PS', iconColor: '#fcf3cf',
    description: 'Hedefi kalkanlar; 30 saniye boyunca 48 hasar emer.',
  },
  renew: {
    id: 'renew', name: 'Yenilenme', class: 'priest', learnLevel: 8,
    cost: 30, castTime: 0, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'hot', total: 45, duration: 15, interval: 3 }],
    ranks: [
      { rank: 2, level: 14, cost: 50, effects: [{ type: 'hot', total: 90, duration: 15, interval: 3 }] },
      { rank: 3, level: 20, cost: 75, effects: [{ type: 'hot', total: 140, duration: 15, interval: 3 }] },
    ],
    icon: 'RN', iconColor: '#abebc6',
    description: 'Hedefi 15 saniye boyunca toplam $d iyileştirir.',
  },
  mind_blast: {
    id: 'mind_blast', name: 'Zihin Patlaması', class: 'priest', learnLevel: 10,
    cost: 50, castTime: 1.5, cooldown: 8, range: 30, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 42, max: 46 }],
    ranks: [
      { rank: 2, level: 14, cost: 70, effects: [{ type: 'directDamage', min: 60, max: 66 }] },
      { rank: 3, level: 20, cost: 95, effects: [{ type: 'directDamage', min: 86, max: 94 }] },
    ],
    icon: 'MB', iconColor: '#bb8fce',
    description: 'Hedefin zihnini $d Gölge hasarıyla patlatır.',
  },
  heal: {
    id: 'heal', name: 'İyileştirme', class: 'priest', learnLevel: 14,
    cost: 95, castTime: 2.5, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 165, max: 195 }],
    ranks: [{ rank: 2, level: 20, cost: 130, effects: [{ type: 'heal', min: 230, max: 270 }] }],
    icon: 'HE', iconColor: '#fdf2c7',
    description: 'Dost bir hedefi $d kadar iyileştiren yavaş ama güçlü bir dua.',
  },
  mind_flay: {
    id: 'mind_flay', name: 'Zihin Yüzme', class: 'priest', learnLevel: 16,
    cost: 45, castTime: 0, channel: { duration: 3, ticks: 3 }, cooldown: 0, range: 20, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'drainTick', min: 12, max: 12, healFrac: 0 }],
    icon: 'MF', iconColor: '#7d3c98',
    description: 'Hedefin zihnine Gölge enerjisiyle saldırır; 3 saniye boyunca saniyede 12 hasar verir.',
  },
  flash_heal: {
    id: 'flash_heal', name: 'Hızlı İyileştirme', class: 'priest', learnLevel: 20,
    cost: 75, castTime: 1.5, cooldown: 0, range: 30, school: 'holy',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 120, max: 142 }],
    icon: 'FH', iconColor: '#fef9e7',
    description: 'Dost bir hedefi $d kadar iyileştiren hızlı bir dua.',
  },

  // ====================== SHAMAN ======================
  lightning_bolt: {
    id: 'lightning_bolt', name: 'Yıldırım Oku', class: 'shaman', learnLevel: 1,
    cost: 15, castTime: 1.5, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 15, max: 17 }],
    ranks: [
      { rank: 2, level: 8, cost: 25, castTime: 2.0, effects: [{ type: 'directDamage', min: 26, max: 30 }] },
      { rank: 3, level: 14, cost: 40, castTime: 2.5, effects: [{ type: 'directDamage', min: 45, max: 51 }] },
      { rank: 4, level: 20, cost: 60, castTime: 3.0, effects: [{ type: 'directDamage', min: 75, max: 85 }] },
    ],
    icon: 'LB', iconColor: '#85c1e9',
    description: '$d Doğa hasarı veren bir yıldırım fırlatır.',
  },
  rockbiter_weapon: {
    id: 'rockbiter_weapon', name: 'Kayakıran Silahı', class: 'shaman', learnLevel: 1,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'imbue', bonus: 5, duration: 300 }],
    ranks: [
      { rank: 2, level: 8, cost: 30, effects: [{ type: 'imbue', bonus: 9, duration: 300 }] },
      { rank: 3, level: 16, cost: 45, effects: [{ type: 'imbue', bonus: 14, duration: 300 }] },
    ],
    icon: 'RB', iconColor: '#b9770e',
    description: 'Silahına taşın öfkesini işler: 5 dakika boyunca her savuruş 5 ek hasar verir.',
  },
  healing_wave: {
    id: 'healing_wave', name: 'İyileştirme Dalgası', class: 'shaman', learnLevel: 1,
    cost: 25, castTime: 1.5, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 36, max: 44 }],
    ranks: [
      { rank: 2, level: 6, cost: 40, castTime: 2.0, effects: [{ type: 'heal', min: 56, max: 68 }] },
      { rank: 3, level: 12, cost: 65, castTime: 2.5, effects: [{ type: 'heal', min: 92, max: 110 }] },
      { rank: 4, level: 18, cost: 90, castTime: 2.5, effects: [{ type: 'heal', min: 138, max: 164 }] },
    ],
    icon: 'HW', iconColor: '#aed6f1',
    description: 'Dost bir hedefi $d kadar iyileştirir.',
  },
  earth_shock: {
    id: 'earth_shock', name: 'Toprak Şoku', class: 'shaman', learnLevel: 4,
    cost: 30, castTime: 0, cooldown: 6, range: 20, school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 19, max: 22 }],
    ranks: [
      { rank: 2, level: 10, cost: 45, effects: [{ type: 'directDamage', min: 33, max: 38 }] },
      { rank: 3, level: 16, cost: 65, effects: [{ type: 'directDamage', min: 54, max: 61 }] },
    ],
    icon: 'ES', iconColor: '#b9770e',
    description: 'Hedefi sarsıcı bir güçle anında şoklar; $d Doğa hasarı verir.',
  },
  lightning_shield: {
    id: 'lightning_shield', name: 'Yıldırım Kalkanı', class: 'shaman', learnLevel: 8,
    cost: 25, castTime: 0, cooldown: 0, range: 0, school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'thorns', value: 13, duration: 600 }],
    ranks: [
      { rank: 2, level: 12, cost: 40, effects: [{ type: 'selfBuff', kind: 'thorns', value: 20, duration: 600 }] },
      { rank: 3, level: 18, cost: 55, effects: [{ type: 'selfBuff', kind: 'thorns', value: 29, duration: 600 }] },
    ],
    icon: 'LS', iconColor: '#5dade2',
    description: 'Seni çıtırdayan yıldırımla sarar: yakın dövüş saldırganları 13 Doğa hasarı alır.',
  },
  flame_shock: {
    id: 'flame_shock', name: 'Alev Şoku', class: 'shaman', learnLevel: 10,
    cost: 35, castTime: 0, cooldown: 6, range: 20, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 25, max: 25 }, { type: 'dot', total: 28, duration: 12, interval: 3 }],
    ranks: [{
      rank: 2, level: 16, cost: 55,
      effects: [{ type: 'directDamage', min: 42, max: 42 }, { type: 'dot', total: 48, duration: 12, interval: 3 }],
    }],
    icon: 'FS', iconColor: '#e74c3c',
    description: 'Hedefi ateşle dağlar; 25 hasar artı 12 saniye boyunca $d verir.',
  },
  frost_shock: {
    id: 'frost_shock', name: 'Buz Şoku', class: 'shaman', learnLevel: 14,
    cost: 50, castTime: 0, cooldown: 6, range: 20, school: 'frost',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 36, max: 42 }, { type: 'slow', mult: 0.5, duration: 8 }],
    icon: 'FK', iconColor: '#85c1e9',
    description: 'Hedefi buzla anında şoklar; $d Buz hasarı verir ve hareketini 8 saniye boyunca %50 yavaşlatır.',
  },
  ghost_wolf: {
    id: 'ghost_wolf', name: 'Hayalet Kurt', class: 'shaman', learnLevel: 16,
    cost: 35, castTime: 2.0, cooldown: 0, range: 0, school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.4, duration: 600 }],
    icon: 'GW', iconColor: '#aab7b8',
    description: 'Seni Hayalet Kurda dönüştürür; hareket hızını 10 dakika boyunca %40 artırır.',
  },
  stormstrike: {
    id: 'stormstrike', name: 'Fırtına Vuruşu', class: 'shaman', learnLevel: 20,
    cost: 40, castTime: 0, cooldown: 12, range: 0, school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 26 }],
    icon: 'ST', iconColor: '#5dade2',
    description: 'Fırtınayı silahından geçirir; anında silah hasarı artı $d vurur.',
  },

  // ====================== WARLOCK ======================
  shadow_bolt: {
    id: 'shadow_bolt', name: 'Gölge Oku', class: 'warlock', learnLevel: 1,
    cost: 25, castTime: 1.7, cooldown: 0, range: 30, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 13, max: 18 }],
    ranks: [
      { rank: 2, level: 8, cost: 38, castTime: 2.2, effects: [{ type: 'directDamage', min: 24, max: 31 }] },
      { rank: 3, level: 14, cost: 55, castTime: 2.7, effects: [{ type: 'directDamage', min: 42, max: 53 }] },
      { rank: 4, level: 20, cost: 80, castTime: 3.0, effects: [{ type: 'directDamage', min: 68, max: 84 }] },
    ],
    icon: 'SB', iconColor: '#9b59b6',
    description: 'Düşmana $d Gölge hasarı veren karanlık bir ok gönderir.',
  },
  demon_skin: {
    id: 'demon_skin', name: 'İblis Derisi', class: 'warlock', learnLevel: 1,
    cost: 20, castTime: 0, cooldown: 0, range: 0, school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 30, duration: 1800 }],
    ranks: [
      { rank: 2, level: 12, cost: 35, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 55, duration: 1800 }] },
      { rank: 3, level: 20, cost: 50, effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 80, duration: 1800 }] },
    ],
    icon: 'DS', iconColor: '#7d6608',
    description: 'İblis derisi, zırhını 30 dakika boyunca 30 artırır.',
  },
  immolate: {
    id: 'immolate', name: 'Yakma', class: 'warlock', learnLevel: 1,
    cost: 25, castTime: 2.0, cooldown: 0, range: 30, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 11, max: 11 }, { type: 'dot', total: 20, duration: 15, interval: 3 }],
    ranks: [{
      rank: 2, level: 10, cost: 40,
      effects: [{ type: 'directDamage', min: 22, max: 22 }, { type: 'dot', total: 35, duration: 15, interval: 3 }],
    }, {
      rank: 3, level: 16, cost: 60,
      effects: [{ type: 'directDamage', min: 38, max: 38 }, { type: 'dot', total: 60, duration: 15, interval: 3 }],
    }],
    icon: 'IM', iconColor: '#e67e22',
    description: 'Düşmanı 11 Ateş hasarıyla yakar; 15 saniye boyunca ek $d hasar verir.',
  },
  corruption: {
    id: 'corruption', name: 'Yozlaşma', class: 'warlock', learnLevel: 4,
    cost: 35, castTime: 2.0, cooldown: 0, range: 30, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 40, duration: 18, interval: 3 }],
    ranks: [
      { rank: 2, level: 12, cost: 55, effects: [{ type: 'dot', total: 72, duration: 18, interval: 3 }] },
      { rank: 3, level: 18, cost: 75, effects: [{ type: 'dot', total: 108, duration: 18, interval: 3 }] },
    ],
    icon: 'CO', iconColor: '#6c3483',
    description: 'Hedefi yozlaştırır; 18 saniye boyunca $d Gölge hasarı verir.',
  },
  life_tap: {
    id: 'life_tap', name: 'Can Emme', class: 'warlock', learnLevel: 6,
    cost: 0, castTime: 0, cooldown: 0, range: 0, school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'lifeTap', hp: 30, mana: 30 }],
    ranks: [
      { rank: 2, level: 14, cost: 0, effects: [{ type: 'lifeTap', hp: 55, mana: 55 }] },
      { rank: 3, level: 20, cost: 0, effects: [{ type: 'lifeTap', hp: 85, mana: 85 }] },
    ],
    icon: 'LT', iconColor: '#76448a',
    description: '30 canı 30 manaya çevirir.',
  },
  curse_of_agony: {
    id: 'curse_of_agony', name: 'Izdırap Laneti', class: 'warlock', learnLevel: 8,
    cost: 25, castTime: 0, cooldown: 0, range: 30, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 36, duration: 24, interval: 3 }],
    ranks: [
      { rank: 2, level: 14, cost: 40, effects: [{ type: 'dot', total: 72, duration: 24, interval: 3 }] },
      { rank: 3, level: 20, cost: 60, effects: [{ type: 'dot', total: 112, duration: 24, interval: 3 }] },
    ],
    icon: 'CA', iconColor: '#512e5f',
    description: 'Hedefi ızdırapla lanetler: 24 saniye boyunca $d Gölge hasarı.',
  },
  drain_life: {
    id: 'drain_life', name: 'Yaşam Çekme', class: 'warlock', learnLevel: 10,
    cost: 35, castTime: 0, channel: { duration: 5, ticks: 5 }, cooldown: 0, range: 20, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'drainTick', min: 7, max: 7, healFrac: 1 }],
    ranks: [
      { rank: 2, level: 14, cost: 50, effects: [{ type: 'drainTick', min: 12, max: 12, healFrac: 1 }] },
      { rank: 3, level: 20, cost: 70, effects: [{ type: 'drainTick', min: 17, max: 17, healFrac: 1 }] },
    ],
    icon: 'DL', iconColor: '#a569bd',
    description: 'Hedefin yaşamını çeker; 5 saniye boyunca saniyede 7 canı sana aktarır.',
  },
  fear: {
    id: 'fear', name: 'Korku', class: 'warlock', learnLevel: 14,
    cost: 40, castTime: 1.5, cooldown: 0, range: 20, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'incapacitate', duration: 8 }],
    icon: 'FE', iconColor: '#5b2c6f',
    description: 'Düşmanın içine dehşet salar; onu 8 saniyeye kadar sinmiş bırakır. Her türlü hasar etkiyi bozar.',
  },
  searing_pain: {
    id: 'searing_pain', name: 'Dağlayan Acı', class: 'warlock', learnLevel: 16,
    cost: 35, castTime: 1.5, cooldown: 0, range: 30, school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 30, max: 38 }],
    icon: 'SP', iconColor: '#dc7633',
    description: 'Düşmanı ızdırap verici ateşle dağlar; $d Ateş hasarı verir. Hızlı okunur.',
  },
  shadowburn: {
    id: 'shadowburn', name: 'Gölge Yanığı', class: 'warlock', learnLevel: 20,
    cost: 70, castTime: 0, cooldown: 15, range: 20, school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 56, max: 66 }],
    icon: 'SH', iconColor: '#6c3483',
    description: 'Hedefi Gölge Aleviyle anında patlatır; $d Gölge hasarı verir.',
  },

  // ====================== DRUID ======================
  wrath: {
    id: 'wrath', name: 'Gazap', class: 'druid', learnLevel: 1,
    cost: 20, castTime: 1.5, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 13, max: 16 }],
    ranks: [
      { rank: 2, level: 8, cost: 32, castTime: 2.0, effects: [{ type: 'directDamage', min: 24, max: 29 }] },
      { rank: 3, level: 14, cost: 48, effects: [{ type: 'directDamage', min: 38, max: 45 }] },
      { rank: 4, level: 20, cost: 70, effects: [{ type: 'directDamage', min: 60, max: 71 }] },
    ],
    icon: 'WR', iconColor: '#58d68d',
    description: '$d Doğa hasarı veren bir doğa enerjisi oku fırlatır.',
  },
  healing_touch: {
    id: 'healing_touch', name: 'İyileştiren Dokunuş', class: 'druid', learnLevel: 1,
    cost: 25, castTime: 2.5, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 37, max: 51 }],
    ranks: [
      { rank: 2, level: 8, cost: 45, castTime: 3.0, effects: [{ type: 'heal', min: 68, max: 86 }] },
      { rank: 3, level: 14, cost: 75, effects: [{ type: 'heal', min: 115, max: 140 }] },
      { rank: 4, level: 20, cost: 110, effects: [{ type: 'heal', min: 175, max: 208 }] },
    ],
    icon: 'HT', iconColor: '#a9dfbf',
    description: 'Dost bir hedefi $d kadar iyileştirir.',
  },
  mark_of_the_wild: {
    id: 'mark_of_the_wild', name: 'Yabanıl İşareti', class: 'druid', learnLevel: 1,
    cost: 20, castTime: 0, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'buff_armor', value: 25, duration: 1800 }],
    ranks: [
      { rank: 2, level: 10, cost: 35, effects: [{ type: 'buffTarget', kind: 'buff_armor', value: 50, duration: 1800 }] },
      { rank: 3, level: 16, cost: 50, effects: [{ type: 'buffTarget', kind: 'buff_armor', value: 75, duration: 1800 }] },
    ],
    icon: 'MW', iconColor: '#f5cba7',
    description: 'Dost bir hedefe Yabanıl İşareti yerleştirir; zırhı 30 dakika boyunca 25 artırır.',
  },
  moonfire: {
    id: 'moonfire', name: 'Ay Ateşi', class: 'druid', learnLevel: 4,
    cost: 25, castTime: 0, cooldown: 0, range: 30, school: 'arcane',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 9, max: 12 }, { type: 'dot', total: 12, duration: 9, interval: 3 }],
    ranks: [{
      rank: 2, level: 10, cost: 40,
      effects: [{ type: 'directDamage', min: 17, max: 21 }, { type: 'dot', total: 24, duration: 12, interval: 3 }],
    }, {
      rank: 3, level: 16, cost: 60,
      effects: [{ type: 'directDamage', min: 28, max: 34 }, { type: 'dot', total: 40, duration: 12, interval: 3 }],
    }],
    icon: 'MF', iconColor: '#d2b4de',
    description: 'Düşmanı ay ateşiyle yakar; $d Arkana hasarı artı zamanla hasar verir.',
  },
  rejuvenation: {
    id: 'rejuvenation', name: 'Canlandırma', class: 'druid', learnLevel: 4,
    cost: 25, castTime: 0, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'hot', total: 32, duration: 12, interval: 3 }],
    ranks: [
      { rank: 2, level: 10, cost: 40, effects: [{ type: 'hot', total: 56, duration: 12, interval: 3 }] },
      { rank: 3, level: 16, cost: 60, effects: [{ type: 'hot', total: 88, duration: 12, interval: 3 }] },
      { rank: 4, level: 20, cost: 80, effects: [{ type: 'hot', total: 116, duration: 12, interval: 3 }] },
    ],
    icon: 'RJ', iconColor: '#82e0aa',
    description: 'Hedefi 12 saniye boyunca toplam $d iyileştirir.',
  },
  thorns: {
    id: 'thorns', name: 'Dikenler', class: 'druid', learnLevel: 6,
    cost: 20, castTime: 0, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'thorns', value: 3, duration: 600 }],
    ranks: [
      { rank: 2, level: 14, cost: 35, effects: [{ type: 'buffTarget', kind: 'thorns', value: 6, duration: 600 }] },
      { rank: 3, level: 20, cost: 50, effects: [{ type: 'buffTarget', kind: 'thorns', value: 9, duration: 600 }] },
    ],
    icon: 'TH', iconColor: '#7dcea0',
    description: 'Hedeften dikenler fışkırır: yakın dövüş saldırganları 3 Doğa hasarı alır.',
  },
  entangling_roots: {
    id: 'entangling_roots', name: 'Dolayan Kökler', class: 'druid', learnLevel: 8,
    cost: 35, castTime: 1.5, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'root', duration: 12 }],
    ranks: [{
      rank: 2, level: 16, cost: 50,
      effects: [{ type: 'root', duration: 12 }, { type: 'dot', total: 32, duration: 12, interval: 3 }],
    }],
    icon: 'ER', iconColor: '#229954',
    description: 'Hedefi 12 saniyeye kadar yerine kökler.',
  },
  bear_form: {
    id: 'bear_form', name: 'Ayı Formu', class: 'druid', learnLevel: 10,
    cost: 30, castTime: 0, cooldown: 0, range: 0, school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'form_bear', value: 0.65, duration: 3600 }],
    icon: 'BF', iconColor: '#b9770e',
    description: 'Ayıya dönüşürsün; zırhı %65, saldırı gücünü 15 artırır. Büyücü formuna dönmek için tekrar kullan.',
  },
  regrowth: {
    id: 'regrowth', name: 'Yeniden Filizlenme', class: 'druid', learnLevel: 14,
    cost: 55, castTime: 2.0, cooldown: 0, range: 30, school: 'nature',
    requiresTarget: true, targetType: 'friendly',
    effects: [{ type: 'heal', min: 52, max: 62 }, { type: 'hot', total: 49, duration: 21, interval: 3 }],
    icon: 'RG', iconColor: '#58d68d',
    description: 'Dost bir hedefi $d iyileştirir ve 21 saniye boyunca ek miktar yeniler.',
  },
  barkskin: {
    id: 'barkskin', name: 'Kabuk Derisi', class: 'druid', learnLevel: 16,
    cost: 30, castTime: 0, cooldown: 60, range: 0, school: 'nature',
    requiresTarget: false, offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_armor', value: 150, duration: 15 }],
    icon: 'BA', iconColor: '#935116',
    description: 'Derin ağaç kabuğu gibi sertleşir; zırhı 15 saniye boyunca 150 artırır.',
  },
  starfire: {
    id: 'starfire', name: 'Yıldız Ateşi', class: 'druid', learnLevel: 18,
    cost: 80, castTime: 3.0, cooldown: 0, range: 30, school: 'arcane',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 60, max: 74 }],
    icon: 'SF', iconColor: '#d2b4de',
    description: 'Gökten bir yıldız ateşi indirir; $d Arkana hasarı verir.',
  },
};

// Abilities a class knows at a given level, with active rank values resolved.
export function abilitiesKnownAt(cls: PlayerClass, level: number): { def: AbilityDef; rank: number; cost: number; castTime: number; effects: AbilityDef['effects'] }[] {
  const out = [];
  for (const id of CLASSES[cls].abilities) {
    const def = ABILITIES[id];
    if (def.learnLevel > level) continue;
    let rank = 1, cost = def.cost, castTime = def.castTime, effects = def.effects;
    for (const r of def.ranks ?? []) {
      if (r.level <= level) {
        rank = r.rank;
        cost = r.cost;
        effects = r.effects;
        if (r.castTime !== undefined) castTime = r.castTime;
      }
    }
    out.push({ def, rank, cost, castTime, effects });
  }
  return out;
}
